### ISSUE TITLE
Error : Gradle version 2.2 is required. Current version is 4.1-milestone-1

### ISSUE THREAD

**Issue by JustTrust** [x2on/gradle-hockeyapp-plugin#105]
Hello, I got this error and I can't understand 4.1 is upper than 2.2.

Error:(38, 0) Gradle version 2.2 is required. Current version is 4.1-milestone-1.
Please fix the project's Gradle settings.

**Comment by x2on** [comment]
4.1-milestone-1 is not a release version. Please use release version of gradle.
