### ISSUE TITLE
automatic release not working?

### ISSUE THREAD

**Issue by sirvon** [x2on/gradle-hockeyapp-plugin#49]
Every time a build is pushed to hockeyapp,
I have to manual go in and release it.

Here's my setup:

```groovy

  hockeyapp {
      apiToken = "2a2b07xxxxxxxxxxxxxx"
      releaseType = 0
      notify = 0
      status = 2
      variantToApiToken = [
              HEBLIVEtv: "d8e3d7axxxxxxxxxxxxxxx"
      ]
  }



```

what gives?
thanks!

**Comment by x2on** [comment]
Hi, probably you are using a token with the wrong rights: http://support.hockeyapp.net/discussions/problems/20467-hockeyapp-doesnt-automatically-release-a-new-uploaded-app-from-jenkins-even-though-downloadnotification-are-checked
