### ISSUE TITLE
No app file found in directory

### ISSUE THREAD

**Issue by jpcmorton** [x2on/gradle-hockeyapp-plugin#51]
I have created a brand new app, followed the instructions provided, however when I run the uploadToHockeyApp task, I get the following error:
*No app file found in directory /Users/jm/Documents/Android/SampleApp/build*
I have only specified my api key. Is there anything else that needs to be specified? Thanks

**Comment by jpcmorton** [comment]
I got it working by specifying the *outputDirectory*. Is this required for Android?

**Comment by x2on** [comment]
Hi @jpcmorton :

no this is not required if you use the android gradle plugin.

Could you please post your `build.gradle`?

**Comment by jpcmorton** [comment]
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.0'
        classpath 'de.felixschulze.gradle:gradle-hockeyapp-plugin:3.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}


repositories {
    mavenCentral()
}

allprojects {
    repositories {
        jcenter()
    }
}

apply plugin: 'de.felixschulze.gradle.hockeyapp'

hockeyapp {
    apiToken = "APITOKEN"
    outputDirectory = 'app/build/outputs/apk'
    appFileNameRegex = '.*.apk'
}
```

**Comment by x2on** [comment]
When you remove `appFileNameRegex` and `outputDirectory` it should work automatically?

**Comment by jpcmorton** [comment]
No, I get 
```
No applicationFile found or no appFileNameRegex provided.
```
I am using Android Gradle on OSX 10.10. This is literally a fresh install of android studio and a brand new app after I formatted my computer. But I guess in the end it doesn't matter if I can specify the location of the APK.

**Comment by x2on** [comment]
Could you please run with `--debug` and post the output about the location of the apk?

**Comment by x2on** [comment]
I'm closing this issue during inactivity. Please feel free to open again if the issue is not solved.

**Comment by Xerosigma** [comment]
I'm having the same issue as well. Will post log shortly
