### ISSUE TITLE
Support for custom upload url

### ISSUE THREAD

**Issue by tnache** [x2on/gradle-hockeyapp-plugin#53]
Hi, 

I have checked the source of the plugin and noticed that there is no option to provide a custom upload url. Plugin always assumes it has to upload builds on https://rink.hockeyapp.net/.

If not available yet, could the support for providing custom hockey app upload url be implemented in some of the next releases?

Thanks in advance.

Best regards,
Tsvetan

**Comment by x2on** [comment]
Hi,

so you run HockeyApp on your own server? (HockeyKit?)
Is the API the same?

**Comment by tnache** [comment]
Hi,

I have to upload my apps to a white labeled version of Hockey App (Hockey
Kit). The API I assume is the same, since I use HockeyAppSDK-3.0.5.jar for
the integration of check for updates and  crash monitoring.

Best regards,
Tsvetan

**Comment by tnache** [comment]
Great. Thanks for the support. I will try it in the next days.

Best regards,
Tsvetan

Felix Schulze <notifications@github.com> schrieb am Mo., 23. März 2015
15:45:
