### ISSUE TITLE
Non asci symbols in release notes.

### ISSUE THREAD

**Issue by demand2k** [x2on/gradle-hockeyapp-plugin#57]
There are "??????" symbols instead of "привет" for non ASCII symbols in release notes. I think UTF-8 in request may correct this problem.

**Comment by x2on** [comment]
Could you use these symbols directly in HockeyApp?

**Comment by demand2k** [comment]
Yes, sure. I'm trying to use cyrillic symbols inside release note. It's ok if I create this directly on site.

**Comment by x2on** [comment]
Is fixed in the 3.2 release which will be available in a few hours.
