### ISSUE TITLE
How can I add flavor support

### ISSUE THREAD

**Issue by dilipc** [x2on/gradle-hockeyapp-plugin#59]
We have project with different flavors -- flavor1 (default app) and flavor2 (branded app).  Most of the code is shared between those flavors except package name and logo. We have created two separate apps on Hockey, so we will need to provide two different appId in gradle file.  I see there is a way to map variant to application id, but is there a way to map flavor to application id?

Thanks,
Dilip

**Comment by CharlesHarley** [comment]
The build variant is a combination of the flavour and the build type. See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Type-Product-Flavor-Build-Variant for a full explanation.

Here is an example of how you would define the application ids for a 'free' and 'paid' flavour:

```groovy
hockeyapp {
    apiToken = '12345'
    variantToApplicationId = [
            freeDebug  : '12345',
            freeRelease: '12345',
            paidDebug  : '12345',
            paidRelease: '12345',
    ]
}
```

**Comment by x2on** [comment]
Thanks @CharlesHarley for explanation.
