### ISSUE TITLE
Bug in variantToReleaseType 

### ISSUE THREAD

**Issue by mbre77** [x2on/gradle-hockeyapp-plugin#63]
Hi

You've built a great plugin and I'd be happy to use it. But - there is a bug in setting the releaseType using variantToReleaseType. You're setting the releaseType variable correct, but then you use the hockeyApp.releaseType instead of the correct var.

Could you please fix this asap and release a new version?

String releaseType = hockeyApp.releaseType
        if (hockeyApp.variantToReleaseType) {
            if (hockeyApp.variantToReleaseType[variantName]) {
                releaseType = hockeyApp.variantToReleaseType[variantName]
            }
        }
        if (releaseType) {
            entityBuilder.addPart("release_type", new StringBody(hockeyApp.releaseType as String))
        }

Thanks!

**Comment by x2on** [comment]
Would love to see a PR for this fix!

**Comment by edouardouvrard** [comment]
https://github.com/x2on/gradle-hockeyapp-plugin/pull/66 fix this issue but did you know when it can be release on maven central ?

**Comment by x2on** [comment]
Hi @edouardouvrard,

i will make a release on Monday.

Best

**Comment by edouardouvrard** [comment]
Thanks @x2on

**Comment by x2on** [comment]
Fixed in 3.2.1

**Comment by mbre77** [comment]
Thanks
