### ISSUE TITLE
Since 3.2.1 uploadDebugToHockeyApp is not working anymore

### ISSUE THREAD

**Issue by jleidgens** [x2on/gradle-hockeyapp-plugin#70]
With Version 3.2 the command uploadDebugToHockeyApp works fine. With 3.2.1 it does not upload a version but it also does not give an error message why nothing was uploaded.

**Comment by x2on** [comment]
Could you please provide some more details, are u using gradle-android-plugin? Could you please provide the parts from your `build.gradle`

**Comment by jleidgens** [comment]
Sure. 

Main gradle:

    buildscript {
       repositories {
          jcenter()
       }
       dependencies {
          classpath 'com.android.tools.build:gradle:1.3.0'
          classpath 'com.github.ben-manes:gradle-versions-plugin:0.11.3'
          // Assists in working with annotation processors for Android Studio.
          classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
          classpath 'de.felixschulze.gradle:gradle-hockeyapp-plugin:3.3'
       }
    }

And in the App gradle file: 

    apply plugin: 'de.felixschulze.gradle.hockeyapp'
    ...
    buildToolsVersion "23.0.1"
    ...

    hockeyapp {
       apiToken = "1234567890"
    }

Debug Output: 

11:48:25.292 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :app:uploadDebugToHockeyApp
11:48:25.293 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':app:uploadDebugToHockeyApp'
11:48:25.293 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':app:uploadDebugToHockeyApp' is up-to-date
11:48:25.293 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':app:uploadDebugToHockeyApp' (up-to-date check took 0.0 secs) due to: Task.upToDateWhen is false.
11:48:25.294 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':app:uploadDebugToHockeyApp'.
11:48:25.294 [DEBUG] [org.gradle.api.Task] Using android application variants
11:48:25.302 [DEBUG] [org.gradle.api.Task] Obfuscation is not used
11:48:25.303 [LIFECYCLE] [org.gradle.api.Task] App file: /Path/application-android/app/build/outputs/apk/app-debug.apk
11:48:25.314 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':app:uploadDebugToHockeyApp'
11:48:25.315 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :app:uploadDebugToHockeyApp (Thread[Daemon worker Thread 7,5,main]) completed. Took 0.023 secs.
11:48:25.315 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 7,5,main]] finished, busy: 0.338 secs, idle: 0.021 secs
11:48:25.315 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskGraphExecuter] Timing: Executing the DAG took 0.37 secs
11:48:25.316 [LIFECYCLE] [org.gradle.BuildResultLogger] 
11:48:25.316 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD SUCCESSFUL
11:48:25.316 [LIFECYCLE] [org.gradle.BuildResultLogger]

**Comment by panzerfahrer** [comment]
+1

I upgraded to 3.3 last week and noticed that uploads wouldn't appear online. Until today I thought I somehow broke my config. Downgrading back to 3.2 makes the uploads work again.

I didn't do any in-depth debugging here. Just noticed that the log line telling that the upload is in progress ( `:app:upload...`) is rushing through like it is not doing anything.

**Comment by x2on** [comment]
@jleidgens is the file `app-debug.apk` really present after your build?

**Comment by jleidgens** [comment]
Sorry I don't have much time to debug this at the moment. I did a full clean on my project and then executed the uploadDebugToHockeyApp task. After that the apk can be found in the output folder but is not uploaded to hockey.

**Comment by jplorandi** [comment]
It seems it now needs the section variantToApplicationId to work at all. I would suggest an appId config parameter to be added to fall back upon:

HockeyAppUploadTask, lines 138-151
```
String appId = null
        if (hockeyApp.variantToApplicationId) {
            appId = hockeyApp.variantToApplicationId[variantName]
            if (!appId) {
                if(project.getGradle().getTaskGraph().hasTask(uploadAllPath)) {
                    logger.error("Could not resolve app ID for variant: ${variantName} in the variantToApplicationId map.")
                } else {
                    throw new IllegalArgumentException("Could not resolve app ID for variant: ${variantName} in the variantToApplicationId map.")
                }
            }
        }
        if(appId) {
            uploadAppplicationFileToHockeyApp(applicationFile, mappingFile, appId)
        }
```

**Comment by x2on** [comment]
Yes there was the bug. I will make a bugfix release soon. Thanks for your help
