### ISSUE TITLE
Usage on Readme.md points to a non-existent version

### ISSUE THREAD

**Issue by tkirshboim** [x2on/gradle-hockeyapp-plugin#73]
Hello!
It looks like the Readme was updated with the latest version before the release on maven central was done. The documentation [points to version 3.4](https://github.com/x2on/gradle-hockeyapp-plugin/blob/75926c195cb110c86f8d3d1cb20eaf953df76f4d/README.md) but on Maven Central [the latest version is 3.3.1](http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22de.felixschulze.gradle%22%20AND%20a%3A%22gradle-hockeyapp-plugin%22).

**Comment by x2on** [comment]
Thanks for the hint.

**Comment by tkirshboim** [comment]
Gerne. That was a quick fix :speedboat: :+1:
