### ISSUE TITLE
mapping.txt not uploaded with Android gradle plugin 1.5.0

### ISSUE THREAD

**Issue by tkirshboim** [x2on/gradle-hockeyapp-plugin#74]
I'm using the following plugin versions in my build.gradle:
```gradle
buildscript {
    // ...
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'
        classpath 'de.felixschulze.gradle:gradle-hockeyapp-plugin:3.3.1'
    }
}
```
I could upload the apk but then when I checked on HockeyApp I realized that the ```mapping.txt``` file was not uploaded. I ran ```./gradlew uploadReleaseToHockeyApp --debug``` and saw this:
```
17:51:26.104 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':app:uploadReleaseToHockeyApp'.
17:51:26.105 [DEBUG] [org.gradle.api.Task] Using android application variants
17:51:26.111 [DEBUG] [org.gradle.api.Task] Obfuscation is not used
```

When I use the Android gradle plugin version 1.3.1 it works fine and the mapping file is uploaded.
Wild guess : perhaps the API of the plugin was changed and the ```applicationVariant.getObfuscation()``` method that is used [here](https://github.com/x2on/gradle-hockeyapp-plugin/blob/75926c195cb110c86f8d3d1cb20eaf953df76f4d/src/main/groovy/de/felixschulze/gradle/HockeyAppUploadTask.groovy#L89) doesn't exist anymore? I didn't investigate this further..

**Comment by x2on** [comment]
Hi,

thanks for your bug report.
The method is still available - but i see the same result with the missing `mapping.txt` on our project. 
I will investigate this tomorrow why this happens.

**Comment by x2on** [comment]
Looks like `applicationVariant.getObfuscation()` is broken - i now use `getMappingFile()` instead.

**Comment by x2on** [comment]
New version (3.4) is released and should be available in 1-2 hours.

**Comment by tkirshboim** [comment]
Thanks. I'll give it a try.

**Comment by x2on** [comment]
I also created a ticket for the gradle-android-plugin: https://code.google.com/p/android/issues/detail?id=195983

**Comment by tkirshboim** [comment]
works with version 3.4 :+1: :top:
