### ISSUE TITLE
Uploading file size different than the actual file size

### ISSUE THREAD

**Issue by VannesEventurers** [x2on/gradle-hockeyapp-plugin#88]
Hi, I have used ProgressHttpEntityWrapper.java in order to find the uploading file size. So i have convert the transferred & total bytes into B, KB, MB, GB using the below method,

 public String getFileSize(long size) {
        if (size <= 0)
            return "0";
        final String[] units = new String[] { mContext.getResources().getString(R.string.bytes), mContext.getResources().getString(R.string.kilo_bytes), mContext.getResources().getString(R.string.mega_bytes), mContext.getResources().getString(R.string.giga_bytes), mContext.getResources().getString(R.string.tera_bytes) };
        int digitGroups = (int) (Math.log10(size) / Math.log10(1024));
        return new DecimalFormat("#,##0.#").format(size / Math.pow(1024, digitGroups)) + " " + units[digitGroups];
    }

but it gives wrong file size.

For example, my actual file size 297.1 KB but it show the total file size is 365.5 KB. Why the actual file size and uploaing file size gets vary. Could you please suggest me any idea?

**Comment by x2on** [comment]
That could to to many issues.
Filesystem overhead, Kilobyte != Kibibyte and a lot of other reasons.

**Comment by VannesEventurers** [comment]
In ProgressHttpEntityWrapper. java there is a method to get the uploading progress.

 private String getCurrentProgress() {
            Log.d("ss", "Progress getCurrentProgress Total bytes upload     "+totalBytes+" "+transferred);
            String remainingBytes = mFileManager.getFileSize(transferred)+mContext.getString(R.string.of)+mFileManager.getFileSize(totalBytes);
            return remainingBytes;
        }

Actually i'm uploading a file. The actual size of that file is 20680 bytes.  But inside getCurrentProgress() method i'm getting  totalBytes as 237354. My doubt is, why the totalBytes gets vary? do you have any idea please.

**Comment by VannesEventurers** [comment]
I'm in urgent need of this. Please reply me as soon as possible.

**Comment by x2on** [comment]
Sorry but the `ProgressHttpEntityWrapper` is not build for getting the exact filesize. It's just for getting the progress.

**Comment by VannesEventurers** [comment]
okay, thank you for your response. Also i'm found why the exact file size is not returning. Its because we are assigning this call back to the entire entity like below,

ProgressHttpEntityWrapper.ProgressCallback progressCallback = new ProgressHttpEntityWrapper.ProgressCallback() {

        @Override
        public void progress(float progress) {
            //Use the progress
        }

    }

httpPost.setEntity(new ProgressHttpEntityWrapper(entityBuilder.build(), progressCallback));

where i'm my entity not only contain my file it also contain my thumbnail file and other params. So the size gets differ. So i have added my file size with thumbnail size. It will be nearer size of my uploading file size the remaining bytes will be taken for my other params. Now I have Solved it.
