### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by ryacub** [x2on/gradle-hockeyapp-plugin#94]
I'm able to upload the build apk into hockey app, but the install fails.
The apk is always app-release-unsigned.apk regardless of which release type I end up choosing

**Comment by x2on** [comment]
Please post some more details, like your `build.gradle` and which apk's are produced.

**Comment by ryacub** [comment]
I got it to work. I just needed to produce a release candidate build and it would upload properly and the resulting apk is able to install.
